---
- hosts: localhost
  roles:
    - role: bradfordwagner.github-runner
  vars:
    runners_instances: '{{ hosts_to_config[ansible_hostname].instances }}'
    hosts_to_config:
      gh-runner-mba:
        instances: 8
      gh-runner-studio:
        instances: 10
    runners_repos:
      - name: container-base
      - name: gh-template-ansible-playbook
      - name: gh-template-ansible-role
      - name: gh-template-mirror-image
